### ISSUE TITLE
Opam install instructions do not work

### ISSUE THREAD

**Issue by tm507211** [disteph/yicesQS#2]
I first attempted to install using the instructions for opam.

To build I needed to:
1. Install libpoly_bindings from source
2. Install the dev branch of yices2_bindings from source
3. Comment out the tracing module, as Tracing.filedump, Tracing.print, and Tracing.options are not defined.

**Comment by disteph** [comment]
Indeed, I need to update the build instructions, as the current ones are pretty old.

You do need the libpoly bindings (https://github.com/SRI-CSL/libpoly_ocaml_bindings) and the tracing package (https://github.com/disteph/tracing) neither of which are on the opam package repo.

I'll try to update the instructions soon.

**Comment by disteph** [comment]
Did you manage to get a executable that links to the Yices and libpoly C libraries and that runs?

**Comment by disteph** [comment]
I have updated the instructions.

**Comment by tm507211** [comment]
I did manage to get an executable that runs by installing everything from source.

**Comment by disteph** [comment]
OK, awesome. I've detected a few more dependencies I hadn't listed, so I'll add that to the opam files.
